//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;


namespace ASF.Business
{
    /// <summary>
    /// CartItemBusiness business component.
    /// </summary>
    public class CartItemBusiness
    {
        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="cartItem"></param>
        /// <returns></returns>
        public CartItem Add(CartItem cartItem)
        {
            var cartItemDac = new CartItemDac();
            return cartItemDac.Create(cartItem);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var cartItemDac = new CartItemDac();
            cartItemDac.DeleteById(id);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public List<CartItem> All()
        {
            var cartItemDac = new CartItemDac();
            var result = cartItemDac.Select();
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public CartItem Find(int id)
        {
            var cartItemDac = new CartItemDac();
            var result = cartItemDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="cartItem"></param>
        public void Edit(CartItem cartItem)
        {
            var cartItemDac = new CartItemDac();
            cartItemDac.UpdateById(cartItem);
        }
    }
}
