//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;


namespace ASF.Business
{
    /// <summary>
    /// ClientBusiness business component.
    /// </summary>
    public class ClientBusiness
    {
        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="client"></param>
        /// <returns></returns>
        public Client Add(Client client)
        {
            Client result = null;
            var clientDac = new ClientDac();
            if (!clientDac.Exists(client)) {
                result = clientDac.Create(client);
            } else {
                result = clientDac.SelectByUser(client.AspNetUsers);
            }
            return result;
        }


        public bool Exists(Client client) {
            var clientDac = new ClientDac();
            return clientDac.Exists(client);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var clientDac = new ClientDac();
            clientDac.DeleteById(id);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public List<Client> All()
        {
            var clientDac = new ClientDac();
            var result = clientDac.Select();
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Client Find(int id)
        {
            var clientDac = new ClientDac();
            var result = clientDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="client"></param>
        public void Edit(Client client)
        {
            var clientDac = new ClientDac();
            clientDac.UpdateById(client);
        }

        public Client FindByGuid(Guid guid) {
            var clientDac = new ClientDac();
            return clientDac.SelectByGuid(guid);
        }

        public Client FindByName(string name) {
            var clientDac = new ClientDac();
            return clientDac.SelectByName(name);
        }

        public Client FindByUser(string name) {
            var clientDac = new ClientDac();
            return clientDac.SelectByUser(name.Replace("-","."));
        }
    }
}
