//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;


namespace ASF.Business
{
    /// <summary>
    /// OrderBusiness business component.
    /// </summary>
    public class OrderBusiness
    {
        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="order"></param>
        /// <returns></returns>
        public Order Add(Order order)
        {
            var orderDac = new OrderDac();
            return orderDac.Create(order);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var orderDac = new OrderDac();
            orderDac.DeleteById(id);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public List<Order> All()
        {
            var orderDac = new OrderDac();
            var result = orderDac.Select();
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Order Find(int id)
        {
            var orderDac = new OrderDac();
            var result = orderDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="order"></param>
        public void Edit(Order order)
        {
            var orderDac = new OrderDac();
            orderDac.UpdateById(order);
        }

        public Order FindByNumber(int number) {
            var orderDac = new OrderDac();
            var result = orderDac.SelectByNumber(number);
            return result;
        }
    }
}
