//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;


namespace ASF.Business
{
    /// <summary>
    /// ProductBusiness business component.
    /// </summary>
    public class ProductBusiness
    {
        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="product"></param>
        /// <returns></returns>
        public Product Add(Product product)
        {
            var productDac = new ProductDac();
            return productDac.Create(product);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var productDac = new ProductDac();
            productDac.DeleteById(id);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public List<Product> All()
        {
            var productDac = new ProductDac();
            var result = productDac.Select();
            return result;
        }

        public List<Product> GetByName(string name) {
            var productDac = new ProductDac();
            name = "%" + name.Replace(" ", "%") + "%";
            var result = productDac.SelectByName(name);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Product Find(int id)
        {
            var productDac = new ProductDac();
            var result = productDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="product"></param>
        public void Edit(Product product)
        {
            var productDac = new ProductDac();
            productDac.UpdateById(product);
        }

        public List<Product> GetByCartId(int id) {
            var productDac = new ProductDac();
            return productDac.GetByCartId(id);
        }
    }
}
